# Generated by Django 6.0.4 on 2026-04-21 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrapy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('product_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='scrapy_app.productsources')),
            ],
        ),
    ]
