# Generated by Django 6.0.4 on 2026-04-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
        ('users', '0002_remove_userprofile_name_fields'),
    ]

    operations = [
    ]
